// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: internal/proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type RegisterResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponce) Reset() {
	*x = RegisterResponce{}
	mi := &file_internal_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponce) ProtoMessage() {}

func (x *RegisterResponce) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponce.ProtoReflect.Descriptor instead.
func (*RegisterResponce) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponce) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_internal_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *PollRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type TaskEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedData []byte                 `protobuf:"bytes,1,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	InitV         []byte                 `protobuf:"bytes,2,opt,name=init_v,json=initV,proto3" json:"init_v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEnvelope) Reset() {
	*x = TaskEnvelope{}
	mi := &file_internal_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEnvelope) ProtoMessage() {}

func (x *TaskEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEnvelope.ProtoReflect.Descriptor instead.
func (*TaskEnvelope) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *TaskEnvelope) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *TaskEnvelope) GetInitV() []byte {
	if x != nil {
		return x.InitV
	}
	return nil
}

type ResultEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	EncryptedData []byte                 `protobuf:"bytes,2,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	InitV         []byte                 `protobuf:"bytes,3,opt,name=init_v,json=initV,proto3" json:"init_v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultEnvelope) Reset() {
	*x = ResultEnvelope{}
	mi := &file_internal_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultEnvelope) ProtoMessage() {}

func (x *ResultEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultEnvelope.ProtoReflect.Descriptor instead.
func (*ResultEnvelope) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *ResultEnvelope) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ResultEnvelope) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *ResultEnvelope) GetInitV() []byte {
	if x != nil {
		return x.InitV
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{5}
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	FilePath      string                 `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileName      string                 `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileData      []byte                 `protobuf:"bytes,6,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_internal_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Task) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Task) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Task) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Task) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type TaskResult struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	TaskId  string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Command string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Output  string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error   string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// если скачивание с клеинта
	FileName      string `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileChunk     []byte `protobuf:"bytes,6,opt,name=file_chunk,json=fileChunk,proto3" json:"file_chunk,omitempty"`
	IsLast        bool   `protobuf:"varint,7,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_internal_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *TaskResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *TaskResult) GetFileChunk() []byte {
	if x != nil {
		return x.FileChunk
	}
	return nil
}

func (x *TaskResult) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

var File_internal_proto_service_proto protoreflect.FileDescriptor

const file_internal_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/service.proto\x12\x05proto\"y\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\"1\n" +
	"\x10RegisterResponce\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\"*\n" +
	"\vPollRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"L\n" +
	"\fTaskEnvelope\x12%\n" +
	"\x0eencrypted_data\x18\x01 \x01(\fR\rencryptedData\x12\x15\n" +
	"\x06init_v\x18\x02 \x01(\fR\x05initV\"k\n" +
	"\x0eResultEnvelope\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12%\n" +
	"\x0eencrypted_data\x18\x02 \x01(\fR\rencryptedData\x12\x15\n" +
	"\x06init_v\x18\x03 \x01(\fR\x05initV\"\a\n" +
	"\x05Empty\"\xa4\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_data\x18\x06 \x01(\fR\bfileData\"\xc2\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"file_chunk\x18\x06 \x01(\fR\tfileChunk\x12\x17\n" +
	"\ais_last\x18\a \x01(\bR\x06isLast2\xb5\x01\n" +
	"\rClientService\x12;\n" +
	"\bRegister\x12\x16.proto.RegisterRequest\x1a\x17.proto.RegisterResponce\x122\n" +
	"\aGetTask\x12\x12.proto.PollRequest\x1a\x13.proto.TaskEnvelope\x123\n" +
	"\n" +
	"SendResult\x12\x15.proto.ResultEnvelope\x1a\f.proto.Empty(\x01B\x14Z\x12rat/internal/protob\x06proto3"

var (
	file_internal_proto_service_proto_rawDescOnce sync.Once
	file_internal_proto_service_proto_rawDescData []byte
)

func file_internal_proto_service_proto_rawDescGZIP() []byte {
	file_internal_proto_service_proto_rawDescOnce.Do(func() {
		file_internal_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_service_proto_rawDesc), len(file_internal_proto_service_proto_rawDesc)))
	})
	return file_internal_proto_service_proto_rawDescData
}

var file_internal_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_proto_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: proto.RegisterRequest
	(*RegisterResponce)(nil), // 1: proto.RegisterResponce
	(*PollRequest)(nil),      // 2: proto.PollRequest
	(*TaskEnvelope)(nil),     // 3: proto.TaskEnvelope
	(*ResultEnvelope)(nil),   // 4: proto.ResultEnvelope
	(*Empty)(nil),            // 5: proto.Empty
	(*Task)(nil),             // 6: proto.Task
	(*TaskResult)(nil),       // 7: proto.TaskResult
}
var file_internal_proto_service_proto_depIdxs = []int32{
	0, // 0: proto.ClientService.Register:input_type -> proto.RegisterRequest
	2, // 1: proto.ClientService.GetTask:input_type -> proto.PollRequest
	4, // 2: proto.ClientService.SendResult:input_type -> proto.ResultEnvelope
	1, // 3: proto.ClientService.Register:output_type -> proto.RegisterResponce
	3, // 4: proto.ClientService.GetTask:output_type -> proto.TaskEnvelope
	5, // 5: proto.ClientService.SendResult:output_type -> proto.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_service_proto_init() }
func file_internal_proto_service_proto_init() {
	if File_internal_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_service_proto_rawDesc), len(file_internal_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_service_proto_goTypes,
		DependencyIndexes: file_internal_proto_service_proto_depIdxs,
		MessageInfos:      file_internal_proto_service_proto_msgTypes,
	}.Build()
	File_internal_proto_service_proto = out.File
	file_internal_proto_service_proto_goTypes = nil
	file_internal_proto_service_proto_depIdxs = nil
}
